//---------------------------------------------------------------------
// <copyright file="export.h" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//---------------------------------------------------------------------
#pragma once

// This definition is autogenerated by CMake when building the shared library
#if defined(MicrosoftCorrelationVector_EXPORTS)
	#if defined(_MSC_VER)
		//  Microsoft 
		#define EXPORTABLE __declspec(dllexport)
	#elif defined(__GNUC__)
		//  GCC
		#define EXPORTABLE __attribute__((visibility("default")))
	#endif
#else
	#if defined(_MSC_VER)
		//  Microsoft 
		#define EXPORTABLE __declspec(dllimport)
	#endif
#endif

#ifndef EXPORTABLE
	#define EXPORTABLE
#endif
